### ISSUE TITLE
No SMART Details from Disks

### ISSUE THREAD

**Issue by drmany** [edgarsuit/FreeNAS-Report#12]
The SMART list is empty, when i manually read the SMART details from the FreeNAS shell it gives me a normal output with SMART Parameters. I´m running FreeNAS 11.3 U1. If i choose the option to list the SMART parameters of my M.2 drives when i get a normal output in the mail.

![image](https://user-images.githubusercontent.com/62610550/77446588-e3d12500-6dee-11ea-9d2b-9cc85705dee8.png)

**Comment by m-rm** [comment]
Did you enable `includeSSD` in the script?

**Comment by drmany** [comment]
Jap, i enabled that before, because we have the system of two m.2 drives in Raid1. Then i enable "includeSSD" the two m.2 shows up, but all other hard drives are not listet. In the example aboth the option "includeSSD" is disabled.

**Comment by drmany** [comment]
Can it be a naming issue in the script? Because the hard drives have a different name sheme as the m.2 ssd´s?

**Comment by m-rm** [comment]
Hm, maybe. Does `sysctl -n kern.disks` list the drives?

Also check with `smartctl -i /dev/DRIVE` (replace DRIVE with the actual name) if it says `SMART support is: Enabled`.

If that's ok then it may be a parsing issue.

**Comment by drmany** [comment]
So sysctl -n kern.disk showes me all my drives included the two system drives (m.2).
smartctl -i /dev/mydrive told me that SMART support is enabled....

**Comment by m-rm** [comment]
Then it's probably a problem parsing the smartctl output with awk. Unfortunately I don't know awk well enough to be any help.

**Comment by edgarsuit** [comment]
What's the output of `smartctl -A -i` for one of your disks?

**Comment by drmany** [comment]
I found the problem. It´s an issue with the  ` if [ "$(smartctl -i /dev/"${drive}" | grep "SMART support is: Enabled")" ]; then`

The problem is the Space in between "SMART support is:" and the "Enable", its a string that is not variable in length. It must be `egrep "SMART support is:[ \t]+Enabled`. Because its depent on the disks or raid-controller that is in use. You may have diffrent outputs on SMART, the problem is the format of the SMART output and thats the next problem, the m.2 drives have a completly different SMART output than my hard-drives. Now my hard-drives can be read by the script but the script can´t put the informations from SMART output in the table because of the different format from the SMART for my hdds. This explains why the script works with the m.2 ssd.

**Comment by edgarsuit** [comment]
Got it, that makes sense. Can you send me an example output of `smartctl -A -i` for one of you drives so I can work on an update that fixes this issue?

**Comment by drmany** [comment]
Sure, here it is.

The thirst one is the HDD output, the second is the SSD. You think it´s a lot of work? 

![HDDSMART](https://user-images.githubusercontent.com/62610550/77560110-4b55a600-6ebd-11ea-8a35-b3fbddd21b9c.PNG)
![SSDSMART](https://user-images.githubusercontent.com/62610550/77560113-4bee3c80-6ebd-11ea-86a5-2aa62e680d72.PNG)

**Comment by drmany** [comment]
Do you think its alot of work? because i need a this script for my work and been searching for a while to find a functionaly script.

**Comment by edgarsuit** [comment]
Your HDDs are SAS disks, the script isn't intended for use with SAS disks. There's a SAS version of the plaintext-only script here: https://www.ixsystems.com/community/threads/scripts-to-report-smart-zpool-and-ups-status-hdd-cpu-t%C2%B0-hdd-identification-and-backup-the-config.27365/

**Comment by drmany** [comment]
okay, but is it possible to import the SAS-version or an option to choose into this script? Iwant to have one script for the SMART and ZPool and i like the table of this script you can realize fas if a drive fails.

**Comment by edgarsuit** [comment]
Yeah, you can have the data represented in the smartctl output for SAS disks in an emailed table but that's not work I'm going to be able to undertake. Feel free to fork the script and give it a go yourself, it's only a few hundred lines of code.
