### ISSUE TITLE
Scrub Info Incorrect if run in TrueNAS 12 RC1

### ISSUE THREAD

**Issue by JAAlperin** [edgarsuit/FreeNAS-Report#16]
Output of zpool status command is slightly different in CORE, so script requires minor changes in Scrub section:
1. adjust awk print statements for scrubRepBytes, scrubErrors, scrubTime and scrubDate -2.
2. remove "B" from scrubRepBytes

**Comment by ref90** [comment]
Hello JAAlperin

I don't unterstand what to do

Could you please explain which line need to be modified ?

Thanks

**Comment by JAAlperin** [comment]
Search for the lines containing scrubRepBytes, scrubErrors, scrubTime and scrubDate.  Adjust the awk print to two less.

**Comment by ref90** [comment]
Thanks a lot, you are the best :)

**Comment by Bloodpack** [comment]
Solved thank you

**Comment by m-rm** [comment]
Fixed by #18
