### ISSUE TITLE
Used space of Pools not correctly displayed

### ISSUE THREAD

**Issue by mojo1988** [edgarsuit/FreeNAS-Report#19]
Maybe i am wrong. But at the pool menu on the Admin-Website of Freenas there is a different value. 

The script told me for my Tank 55% used and on the website i have 65% of pool usage

Thanks
Johannes

**Comment by edgarsuit** [comment]
This is a known bug in the TrueNAS CORE UI

**Comment by mojo1988** [comment]
oh sry i run freenas 11.3 U4.1

**Comment by edgarsuit** [comment]
No prob. FWIW, the value display in the report comes from `zpool list` and is the correct value. The value on the webUI is always a bit higher.
