### ISSUE TITLE
Getting a weird issue with the date conversion...

### ISSUE THREAD

**Issue by dubl3a** [edgarsuit/FreeNAS-Report#2]
Scrub time is not showing correctly in the emails.  Additionally, I am receiving an additional email now.  I found that these errors are appearing and generating the second email:
```
Failed conversion of ``25-on-Sun_Feb'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``25-on-Sun_Feb'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``25-on-Sun_Feb'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``23-on-Fri_Feb'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
```

Started when I updated to 11.1-U#

**Comment by snagglewest** [comment]
Same issue here...

Anyone have a fix?

**Comment by Scentle5S** [comment]
Using @reven's [fork](https://github.com/reven/FreeNAS-Report/commit/e22d102ba473bef56beca175f1020788ee8f5d1b) fixed the issue for me.

**Comment by reven** [comment]
I know that @edgarsuit was planning on addressing this and other changes he had in mind, but he probably was busy and hasn't gotten around to that. I can push the 1.3 branch to master on my own repo if that's useful for anyone until Jason gets around to implement the changes he wanted?

**Comment by edgarsuit** [comment]
I'll see if I can find some time to update it this weekend

**Comment by edgarsuit** [comment]
Updated script to v1.3, thanks reven for the fix! Also added a column for scrub time on the zpool status table.
