### ISSUE TITLE
FreeNAS 11.2-u8 Failed conversion of ``1-on-Sun_Nov'' using format ``%Y-%b-%e_%H:%M:%S''

### ISSUE THREAD

**Issue by Gnomesenpai** [edgarsuit/FreeNAS-Report#20]
Running FreeNAS 11.2-U8 gives this error, system time/date/zone is set correctly:
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``26-on-Thu_Nov'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``8-on-Sun_Nov'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``25-on-Sun_Oct'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``15-on-Sun_Nov'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``1-on-Sun_Nov'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
Failed conversion of ``22-on-Sun_Nov'' using format ``%Y-%b-%e_%H:%M:%S''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]

**Comment by TnTBass** [comment]
I see the same issue on FreeNAS-11.3-U3.2

**Comment by Iril** [comment]
Howdy, This is also true on TrueNAS 12.0-U1
"Failed conversion of ``7-on-Mon_Sep'' using format ``%Y-%b-%e_%H:%M:%S''"

**Comment by Wolfeman0101** [comment]
I'm having the same issue.

**Comment by edgarsuit** [comment]
Should be resolved with the latest merge
