### ISSUE TITLE
Realloc'd Sectors formating issue after scrub is ran

### ISSUE THREAD

**Issue by dubl3a** [edgarsuit/FreeNAS-Report#4]
[Here](https://i.imgur.com/EzxFIHQ.png) is a screenshot of the Realloc'd Sectors column that has the formatting error.
Here is the text output:
`< td style="text-align:center; background-color:#f4f4f4; height:25px; border:1px solid black; border-collapse:collapse; font-family:courier;">0`
I'm using version 1.3 and am unsure why this is occurring after a scrub is completed.

**Comment by edgarsuit** [comment]
Can you post a screenshot of what the rest of the table looks like? I want to see if there's a weird value in an adjacent cell that's being captured as HTML.

If you can, capture the raw HTML of the email message and put that in a pastebin.

**Comment by dubl3a** [comment]
[Here ](https://pastebin.com/gEJ7qBVf)is the pastebin and it appears to be on line 83.  [Here](https://i.imgur.com/ysFwkcn.png) is the screenshot too just in case.  Somehow, a space is being created after a scrub is performed.

**Comment by edgarsuit** [comment]
Thanks, let me stare at these for a while... I think it's automatically wrapping the lines and you happened to get a line break in the middle of an HTML tag. I'll try to manually insert line breaks in to see if that fixes it. I've got a busy few days ahead of me, so it'll probably be next week before it happens.

**Comment by dubl3a** [comment]
Take all the time you need as this is only a mild inconvenience.  I greatly appreciate your time!

**Comment by edgarsuit** [comment]
Just made an update and tested it, the HTML output is now a lot cleaner and has linebreaks in the area you were having issues with. Check it out to see if this fixes the issue.

**Comment by dubl3a** [comment]
Just tested it and it looks a ton better!  Thanks again!
