### ISSUE TITLE
Timestamp issue

### ISSUE THREAD

**Issue by ligistx** [edgarsuit/FreeNAS-Report#5]
I am not sure what is causing this, I think it started when I virtualized freenas under ESXi but I didn't pay enough attention to when this happened to cross reference when I virtualized.

I get this error:

`date: illegal option -- 0
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
date: illegal option -- 2
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[[[cc]yy]mm]dd]HH]MM[.ss]] [+format]
`

**Comment by edgarsuit** [comment]
I'm afraid you're on your own for this one. I don't have an ESX environment to test in. If you need to, just insert a static string where there are date() calls and work backward from there.

**Comment by ligistx** [comment]
Actually, I got it fixed. Not sure if this is worth looking into, but when I went to ESXi I accidentally chose 11.0U4 instead of 11.1U4 ISO. I am now on 11.1U6 and its fixed. 

Must be an issue with 11.0U4.

**Comment by edgarsuit** [comment]
Glad to hear that. They did change a few things going from U4 to U6 that we had to fix, so that's most likely your issue. Thanks for circling back :)
