### ISSUE TITLE
Unable to extract information from DELL SAS drives

### ISSUE THREAD

**Issue by sehang** [edgarsuit/FreeNAS-Report#9]
> if [ "$(smartctl -i /dev/"${drive}" | grep "SMART support is: Enabled")" ] && ! [ "$(smartctl -i /dev/"${drive}" | grep "Solid State Device")" ]; then

If I change the above line in the shell script to:

if [ "$(smartctl -i /dev/"${drive}" | grep "SMART support is:[[:space:]]*Enabled")" ] && ! [ "$(smartctl -i /dev/"${drive}" | grep "Solid State Device")" ]; then

The SMART information are still incorrect: https://imgur.com/VqPe34G
```
# smartctl -i /dev/da23
smartctl 6.5 2016-05-07 r4318 [FreeBSD 11.0-STABLE amd64] (local build)
Copyright (C) 2002-16, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Vendor:               HITACHI
Product:              HUS723030ALS640
Revision:             M2D4
Compliance:           SPC-4
User Capacity:        3,000,592,982,016 bytes [3.00 TB]
Logical block size:   512 bytes
Rotation Rate:        7200 rpm
Form Factor:          3.5 inches
Logical Unit id:      0x5000cca03e5d1e24
Serial number:        ********
Device type:          disk
Transport protocol:   SAS (SPL-3)
Local Time is:        Sun Jan 13 07:56:06 2019 CST
SMART support is:     Available - device has SMART capability.
SMART support is:     Enabled
Temperature Warning:  Disabled or Not Supported
```

**Comment by edgarsuit** [comment]
SAS drives aren't supported. There's an ASCII-only version on the FreeNAS forums that supports SAS drives.
